### ISSUE TITLE
docker is crashing after a while

### ISSUE THREAD

**Issue by uv-orbs** [ton-foundation/ton-api-v4#3]
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ADNLClient instance at:
    at ADNLClient.onError (/app/node_modules/ton-lite-client/dist/adnl/client.js:124:14)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by Just3F** [comment]
Have almost the same problem

node:events:491
2023-03-07 00:02:57       throw er; // Unhandled 'error' event
2023-03-07 00:02:57       ^
2023-03-07 00:02:57 
2023-03-07 00:02:57 Error: connect ECONNREFUSED 51.195.189.59:19434
2023-03-07 00:02:57     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
2023-03-07 00:02:57 Emitted 'error' event on ADNLClient instance at:
2023-03-07 00:02:57     at ADNLClient.onError (/app/node_modules/ton-lite-client/dist/adnl/client.js:124:14)
2023-03-07 00:02:57     at Socket.emit (node:events:513:28)
2023-03-07 00:02:57     at emitErrorNT (node:internal/streams/destroy:157:8)
2023-03-07 00:02:57     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
2023-03-07 00:02:57     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2023-03-07 00:02:57   errno: -111,
2023-03-07 00:02:57   code: 'ECONNREFUSED',
2023-03-07 00:02:57   syscall: 'connect',
2023-03-07 00:02:57   address: '51.195.189.59',
2023-03-07 00:02:57   port: 19434
2023-03-07 00:02:57 }

**Comment by Just3F** [comment]
I have the same problem
